import { chromium } from "playwright";
import { mkdirSync } from "node:fs";
mkdirSync("/tmp/koi-qa10", { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
page.on("pageerror", (err) => console.log("PAGEERROR:", err.message));
const bad = [];
page.on("response", (r) => { if (r.status() >= 400) bad.push(`${r.status()} ${r.url()}`); });
await page.goto("http://localhost:5199/", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(2500);
await page.screenshot({ path: "/tmp/koi-qa10/01-avatar.png" });
const hero = page.locator(".koi-hero-cta");
if (await hero.count()) { await hero.first().click(); await page.waitForTimeout(500); }
await page.screenshot({ path: "/tmp/koi-qa10/02-home.png" });
await page.getByRole("button", { name: "Go on a date" }).click();
await page.locator(".koi-pick").first().click();
await page.locator(".koi-loc").first().click();
await page.getByRole("button", { name: "Meet up" }).click();
await page.waitForSelector(".koi-card", { timeout: 15000 });
await page.waitForTimeout(2000);
await page.screenshot({ path: "/tmp/koi-qa10/03-date.png" });
console.log("bad responses:", bad.length ? bad.join(" | ") : "none");
await browser.close();
